name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  
jobs:
  publish:
    name: Publish package to the Maven Central Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          cache: 'maven'
      - name: Biuld Package
        run: mvn clean package
#      - name: Generate Release notes
#        shell: bash
#        run: |
#          LOG=git log --pretty=oneline $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s" | wc l
      - name: Publish package
        shell: bash
        run: |
          openssl aes-256-cbc -pbkdf2 -iter 100000 -salt -pass pass:${{ env.SONATYPE_ENCRYPTION_PASSWORD }} -in ${{ env.SONATYPE_GPG_DIR }}/secring.gpg.enc -out ${{ env.SONATYPE_GPG_DIR }}/secring.gpg -d;
          openssl aes-256-cbc -pbkdf2 -iter 100000 -salt -pass pass:${{ env.SONATYPE_ENCRYPTION_PASSWORD }} -in ${{ env.SONATYPE_GPG_DIR }}/pubring.gpg.enc -out ${{ env.SONATYPE_GPG_DIR }}/pubring.gpg -d;
          mvn deploy -B -U --settings ${{ env.SONATYPE_GPG_DIR }}/settings.xml -DperformRelease=true -DskipTests=true;
        env:
          SONATYPE_ENCRYPTION_PASSWORD: ${{ secrets.SONATYPE_ENCRYPTION_PASSWORD }}
          SONATYPE_GPG_DIR: './.github'
          SONATYPE_GPG_KEYNAME: ${{ secrets.SONATYPE_GPG_KEYNAME }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
